/*
 * SPI_AD_IO.c
 *
 *  Created on: 2022年6月5日
 *      Author: 62728
 */
#include "xil_io.h"
#include "stdio.h"
#include "xgpio_l.h"
#include "xintc_l.h"
#include "xtmrctr_l.h"
#include "xgpio.h"
#include "xil_exception.h"
#include "xdebug.h"
#include "xparameters.h"
#include "xintc.h"
#include "xuartlite.h"
#include "xuartlite_l.h"

void UART_SEND();
void UART_RECV();
void My_ISR() __attribute__ ((interrupt_handler));
int main() {
	Xil_Out32(XPAR_AXI_UARTLITE_0_BASEADDR + XUL_CONTROL_REG_OFFSET, XUL_CR_FIFO_RX_RESET | XUL_CR_FIFO_TX_RESET);
	Xil_Out32(XPAR_AXI_UARTLITE_1_BASEADDR + XUL_CONTROL_REG_OFFSET, XUL_CR_ENABLE_INTR | XUL_CR_FIFO_RX_RESET | XUL_CR_FIFO_TX_RESET);
	Xil_Out32(XPAR_AXI_UARTLITE_2_BASEADDR + XUL_CONTROL_REG_OFFSET, XUL_CR_ENABLE_INTR | XUL_CR_FIFO_RX_RESET | XUL_CR_FIFO_TX_RESET);
	Xil_Out32(XPAR_AXI_INTC_0_BASEADDR + XIN_IER_OFFSET, XPAR_AXI_UARTLITE_1_INTERRUPT_MASK | XPAR_AXI_UARTLITE_2_INTERRUPT_MASK);
	Xil_Out32(XPAR_AXI_INTC_0_BASEADDR + XIN_MER_OFFSET, XIN_INT_MASTER_ENABLE_MASK | XIN_INT_HARDWARE_ENABLE_MASK);
	microblaze_enable_interrupts();
	while((Xil_In32(XPAR_AXI_UARTLITE_0_BASEADDR + XUL_STATUS_REG_OFFSET) & XUL_SR_RX_FIFO_VALID_DATA) != XUL_SR_RX_FIFO_VALID_DATA);
	Xil_Out32(XPAR_AXI_UARTLITE_2_BASEADDR + XUL_TX_FIFO_OFFSET, Xil_In32(XPAR_AXI_UARTLITE_0_BASEADDR +XUL_RX_FIFO_OFFSET));
	return 0;
}

void My_ISR() {
	int status;
	status = Xil_In32(XPAR_AXI_INTC_0_BASEADDR + XIN_ISR_OFFSET);//读取INTC的中断状态寄存器ISR
	if((status & XPAR_AXI_GPIO_2_IP2INTC_IRPT_MASK) == XPAR_AXI_UARTLITE_2_INTERRUPT_MASK) {//GPIO_2产生中断
		UART_SEND();
	} else if ((status & XPAR_AXI_UARTLITE_1_INTERRUPT_MASK) == XPAR_AXI_UARTLITE_1_INTERRUPT_MASK) {
		UART_RECV();
	}
	Xil_Out32(XPAR_AXI_INTC_0_BASEADDR + XIN_IAR_OFFSET, status);
}

void UART_SEND() {
	while((Xil_In32(XPAR_AXI_UARTLITE_0_BASEADDR + XUL_STATUS_REG_OFFSET) & XUL_SR_RX_FIFO_VALID_DATA) != XUL_SR_RX_FIFO_VALID_DATA);
	Xil_Out32(XPAR_AXI_UARTLITE_2_BASEADDR + XUL_TX_FIFO_OFFSET, Xil_In32(XPAR_AXI_UARTLITE_0_BASEADDR + XUL_RX_FIFO_OFFSET));
}

void UART_RECV() {
	while((Xil_In32(XPAR_AXI_UARTLITE_0_BASEADDR + XUL_STATUS_REG_OFFSET) & XUL_SR_TX_FIFO_EMPTY) != XUL_SR_TX_FIFO_EMPTY);
	Xil_Out32(XPAR_AXI_UARTLITE_0_BASEADDR + XUL_TX_FIFO_OFFSET, Xil_In32(XPAR_AXI_UARTLITE_1_BASEADDR + XUL_RX_FIFO_OFFSET));
}
